import { useState } from "react";

// For commiting changes to the database
import { doc, setDoc, Timestamp, collection, addDoc } from "firebase/firestore";
import db from "../MyFirestore";


/**
 * 
 * @param {Object} post A post object containing data of the post to be edited.
 *                      Null if this form is being used for a new post.
 * 
 * @returns 
 */
const EditPostForm = ({ post, cancelEditingStatus }) => {

    // If no Post object was passed to this component, then it will act to create a New post.
    // Else it will behave as an Edit post form.
    const isNew = (post == null ? true : false);

    // Tracks input form status
    const [title, setTitle] = useState(isNew ? "" : post.title);
    const [content, setContent] = useState(isNew ? "" : post.content);


    // Called when submit is called while the form is in New mode
    const submitNew = async () => {

        if (content === "" && title === "") {
            console.log("incomplete post");
            return;
        }

        // 1. Add a new post without an ID in order to make it autogenerate one.
        // 2. Modify that post to also include "{postId: <this_autogenerated_id>}"
        // This ensures the post id will be unique, doesn't require extra db reads,
        // and still puts the id inside the post document object for reading while editing

        // Create reference to Posts collection
        const postsRef = collection(db, "posts");

        const newPost = {
            title: title,
            content: content,
            timestamp: Timestamp.fromDate(new Date())
        };
        let newPostId = "";
        await addDoc(postsRef, newPost)
            .then(docRef => {
                alert(`New post added: ${docRef.id}`);
                newPostId = docRef.id;
            })
            .catch(error => {
                console.log(error);
            });
        alert(`Parsed new id: ${newPostId}`);
    }

    // Called when submit is called while the form is in Edit mode
    const submitEdit = async () => {
        if ( post.content === content && post.title === title) {
            console.log("no changes made");
            cancelEditingStatus();
            return;
        }

        // Build a new Post object to replace the old
        let updatedPost = post;
        updatedPost.title = title;
        updatedPost.content = content;
        updatedPost.timestamp = Timestamp.fromDate(new Date());
        // Make the change
        await setDoc(doc(db, "posts", `${updatedPost.id}`), updatedPost);

        cancelEditingStatus();
    }

    // Called when the form submit is clicked
    const submit = async () => {
        isNew ? await submitNew() : await submitEdit();
    }

    const cancel = () => {
        cancelEditingStatus();
    }

    const updateTitleCallback = () => {
        const text = document.getElementById("title-field").value;
        setTitle(text);
    }

    const updateContentCallback = () => {
        const text = document.getElementById("content-field").value;
        setContent(text);
    }


    return (
        <form action={submit}>
            <p>Title:</p>
            <textarea type="text"
                id="title-field"
                defaultValue={post?.title}
                onInput={updateTitleCallback}
                rows={1} cols={40}
                />
            
            <p>Content:</p>
            <textarea type="text" 
                id="content-field"
                defaultValue={post?.content}
                onInput={updateContentCallback}
                rows={4} cols={40}
                />

            <br />

            {/* Create cancel button only if in edit mode */}
            {isNew ? <></> :
                <button type="button" onClick={cancel}>Cancel</button>}

            <button type="button" onClick={submit} name="submit" value="submit">Submit</button>
        </form>
    );
};

export default EditPostForm;